name: C/C++ CI

on:
  watch:
    types: [started]
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v2
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v2
    # - name: test
    #   run: make test
      